import { execFileSync, spawnSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { describe, expect, it } from "vitest";

const repoRoot = resolve(__dirname, "..");
const scriptPath = join(repoRoot, "scripts", "install-to-vault.sh");

describe("install-to-vault.sh", () => {
  it("requires the user to pass an explicit vault path", () => {
    expect(() => execFileSync(scriptPath, { cwd: repoRoot, encoding: "utf8" })).toThrow();
  });

  it("explains how to replace the example vault path", () => {
    const result = spawnSync(scriptPath, ["/path/to/your/vault"], {
      cwd: repoRoot,
      encoding: "utf8"
    });

    expect(result.status).toBe(64);
    expect(result.stderr).toBe(
      'Please replace "/path/to/your/vault" with the path to your vault\n'
    );
  });

  it("copies the Obsidian release files into the requested vault plugin folder", () => {
    const tempDir = mkdtempSync(join(tmpdir(), "folder-sort-install-"));
    const vaultPath = join(tempDir, "Vault");

    try {
      const output = execFileSync(scriptPath, [vaultPath], {
        cwd: repoRoot,
        encoding: "utf8"
      });

      const pluginPath = join(vaultPath, ".obsidian", "plugins", "folder-sort");

      expect(readFileSync(join(pluginPath, "manifest.json"), "utf8")).toContain(
        '"id": "folder-sort"'
      );
      expect(readFileSync(join(pluginPath, "main.js"), "utf8")).toContain(
        "THIS IS A GENERATED/BUNDLED FILE BY ESBUILD"
      );
      expect(existsSync(join(pluginPath, "styles.css"))).toBe(false);
      expect(output).toContain("Installing dependencies...");
      expect(output).toContain("Building Folder Sort...");
      expect(output).toContain(pluginPath);
    } finally {
      rmSync(tempDir, { force: true, recursive: true });
    }
  });

  it("removes stale stylesheet artifacts from previous installs", () => {
    const tempDir = mkdtempSync(join(tmpdir(), "folder-sort-install-"));
    const vaultPath = join(tempDir, "Vault");
    const pluginPath = join(vaultPath, ".obsidian", "plugins", "folder-sort");

    try {
      mkdirSync(pluginPath, { recursive: true });
      writeFileSync(join(pluginPath, "styles.css"), "old css");

      execFileSync(scriptPath, [vaultPath], {
        cwd: repoRoot,
        encoding: "utf8"
      });

      expect(existsSync(join(pluginPath, "styles.css"))).toBe(false);
    } finally {
      rmSync(tempDir, { force: true, recursive: true });
    }
  });

  it("does not hard-code a personal vault path", () => {
    expect(existsSync(scriptPath)).toBe(true);

    const script = readFileSync(scriptPath, "utf8");
    const readme = readFileSync(join(repoRoot, "README.md"), "utf8");

    expect(`${script}\n${readme}`).not.toContain("BrainTwo");
    expect(script).toContain("/path/to/your/vault");
  });
});
